config/routes.rb
Subscribem::Engine.routes.draw do
	root "dashboard#index"
	get 'dashboard/index'
	get '/sign_up', to: "accounts#new", as: :sign_up
end

app/models/subscribem/account.rb
module Subscribem
  class Account < ActiveRecord::Base
  end
end

app/controllers/subscribem/accounts_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class AccountsController < ApplicationController
  	def new
  		@account = Subscribem::Account.new
  	end
  end
end

app/controllers/subscribem/application_controller.rb
module Subscribem
  class ApplicationController < ActionController::Base
  end
end

app/controllers/subscribem/dashboard_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class DashboardController < ApplicationController
    def index
    end
  end
end

app/helpers/subscribem/accounts_helper.rb
module Subscribem
  module AccountsHelper
  end
end

app/helpers/subscribem/application_helper.rb
module Subscribem
  module ApplicationHelper
  end
end

app/helpers/subscribem/dashboard_helper.rb
module Subscribem
  module DashboardHelper
  end
end

app/views/layouts/subscribem/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscribem</title>
  <%= stylesheet_link_tag    "subscribem/application", media: "all" %>
  <%= javascript_include_tag "subscribem/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subscribem/accounts/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@account) do |account| %>
	<p>
		<%= account.label :name %> <br>
		<%= account.text_field :name %>
	</p>
	<%= account.submit %>
<% end %>

app/views/subscribem/dashboard/index.html.erb
<%= link_to "Account Sign Up", sign_up_path %>